name: Run Tests On Every Push

on:
  push:
    branches:
      - '**'

jobs:
  test-python:
    runs-on: ubuntu-latest

    name: Python 3.x tests

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y swig cmake g++ make
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Build C++ module
        run: |
          cd python_wrapper
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run Python tests
        env:
          PYTHONPATH: python_wrapper/build  
        run: python python_wrapper/test_find_square.py

